service: default
runtime: python37

entrypoint: gunicorn -b :8080 kratos.wsgi

includes:
  - envs.yaml

handlers:
  - url: /static
    static_dir: static/
    secure: always
    redirect_http_response_code: 301

  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
