# Generated by Django 2.2.6 on 2019-10-13 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agreement',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='gql.Event'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
