# Generated by Django 2.2.6 on 2019-10-14 09:44

from django.db import migrations, models
import gql.utils.random


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0003_event_date'),
    ]

    operations = []
