# Generated by Django 2.2.6 on 2019-10-17 06:39

from django.db import migrations, models
import gql.utils.random


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0006_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(default=gql.utils.random.gen_petname, max_length=64, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
