# Generated by Django 2.2.6 on 2019-10-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0007_auto_20191017_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='status',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONTACTED', 'CONTACTED'), ('QUOTED', 'QUOTED'), ('ACCEPTED', 'ACCEPTED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=255),
        ),
    ]
