# Generated by Django 2.2.6 on 2019-10-18 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0008_auto_20191017_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gql.Service')),
            ],
        ),
        migrations.CreateModel(
            name='CuratedEventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('curated_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gql.CuratedEvent')),
            ],
        ),
    ]
