# Generated by Django 2.2.6 on 2019-10-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0009_auto_20191018_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedevent',
            name='duration',
            field=models.DurationField(default='00:04:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curatedevent',
            name='pax',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curatedevent',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=19),
            preserve_default=False,
        ),
    ]
