# Generated by Django 2.2.6 on 2019-10-24 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0011_auto_20191021_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='starter_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gql.CuratedEvent'),
            preserve_default=False,
        ),
    ]
