# Generated by Django 2.2.6 on 2019-10-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0012_event_starter_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedagreement',
            name='price',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
    ]
