# Generated by Django 2.2.6 on 2019-10-24 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0013_curatedagreement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=14400)),
            preserve_default=False,
        ),
    ]
