# Generated by Django 2.2.6 on 2019-10-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0015_event_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='starter_event',
            new_name='curated_event',
        ),
    ]
