# Generated by Django 2.2.6 on 2019-10-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0016_auto_20191024_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curatedagreement',
            name='price',
        ),
    ]
