# Generated by Django 2.2.6 on 2019-10-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0018_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='max_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='min_quantity',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PriceStructure',
        ),
    ]
