# Generated by Django 2.2.6 on 2019-10-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0019_auto_20191026_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedevent',
            name='is_past_event',
            field=models.BooleanField(default=False),
        ),
    ]
