# Generated by Django 2.2.6 on 2019-10-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0020_curatedevent_is_past_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='My Awesome Event', max_length=255),
            preserve_default=False,
        ),
    ]
