# Generated by Django 2.2.6 on 2019-10-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0021_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='price',
        ),
    ]
