# Generated by Django 2.2.6 on 2019-10-28 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0022_remove_agreement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=19),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UninitializedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('date', models.DateTimeField()),
                ('attendees', models.IntegerField()),
                ('curated_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gql.CuratedEvent')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gql.EventType')),
            ],
        ),
        migrations.CreateModel(
            name='UninitializedAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uninitialized_agreements', to='gql.UninitializedEvent')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uninitialized_agreements', to='gql.Service')),
            ],
        ),
    ]
