# Generated by Django 2.2.6 on 2019-10-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0023_auto_20191028_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='allow_multiple_selection',
            field=models.BooleanField(default=True),
        ),
    ]
