# Generated by Django 2.2.6 on 2019-10-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0024_servicetype_allow_multiple_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='max_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
