# Generated by Django 2.2.6 on 2019-11-01 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0025_auto_20191031_1717'),
        ('gql', '0025_auto_20191101_0025'),
    ]

    operations = [
    ]
