# Generated by Django 2.2.6 on 2019-11-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0026_merge_20191101_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='quotation_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='signed_quotation_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
