# Generated by Django 2.2.6 on 2019-11-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0027_auto_20191101_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='note',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
