# Generated by Django 2.2.6 on 2019-11-10 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0028_event_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedevent',
            name='pax',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='max_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='min_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='gql.ServiceType'),
        ),
        migrations.AlterField(
            model_name='uninitializedevent',
            name='attendees',
            field=models.PositiveIntegerField(),
        ),
    ]
