service: landing
runtime: nodejs10

env_variables:
  PORT: "8080"

handlers:
  - url: /$
    static_files: packages/landing/out/index.html
    upload: packages/landing/out/index.html
    secure: always
    redirect_http_response_code: 301

  - url: /
    static_dir: packages/landing/out
    secure: always
    redirect_http_response_code: 301
